export const EXAMPLE_CODE_LINE_HEIGHT = 22;
export const EXAMPLE_IFRAME_MIN_HEIGHT = 88;
export const EDITOR_SCROLLBAR_SIZE = 12;
export const EDITOR_PADDING_TOP = 12;
export const EXAMPLE_MIN_HEIGHT =
  EXAMPLE_CODE_LINE_HEIGHT * 3 + EDITOR_PADDING_TOP + EDITOR_SCROLLBAR_SIZE;
